sudo: false
language: python
virtualenv:
  system_site_packages: true

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5

addons:
  apt:
    packages:
      - libboost-python-dev
      - libboost-thread-dev
      - libbluetooth-dev

      - libglib2.0-dev
      - libdbus-1-dev
      - libdbus-glib-1-dev
      - libgirepository-1.0-1

      - python-dbus
      - python-gi
      - python3-dbus
      - python3-gi
install:
  - wget https://github.com/labapart/gattlib/releases/download/dev/gattlib_dbus_0.2-dev_x86_64.deb
  - sudo dpkg -i gattlib_dbus_0.2-dev_x86_64.deb
  - pip install codecov nose-exclude pygatt gatt pexpect bluepy


script: coverage run --omit="examples/*" --source=. -m nose tests -v --exclude-dir=examples

after_success:
  - coverage report -m
  - codecov
